---
title: "Data-Carpentry"
author: "Thomas Laurent"
date: "2017年4月24日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE}
#Packages
library("tibble")
library("tidyr")
library("stringr")
library("readr")
library("dplyr")
library("data.table")
```

#Tibble use
```{r}
library("tibble")
tibble(x = 1:3, y = c("A", "B", "C"))
```

```{r}
#Data cleaning
url="https://raw.githubusercontent.com/csgillespie/efficientR/master/extdata/pew.csv"
download.file(url,"extdata/pew.csv")

pew=read.csv(file="./extdata/pew.csv")
pew[1:3, 1:4]

#Long format
dim(pew)
#> [1] 18 10
pewt = gather(data = pew, key = Income, value = Count, -religion)
dim(pewt)
#> [1] 162   3
pewt[c(1:3, 50),]
```
#Separate columns
```{r}
agesex = c("m0-10", "f0-10") # create compound variable
n = c(3, 5) # create a value for each observation
agesex_df = tibble(agesex, n) # create a data frame
separate(agesex_df, col = agesex, into = c("age", "sex"))
```

#String manipulation
```{r}
library(stringr)
```

