---
title: "Visualization"
author: "Thomas Laurent"
date: "2017年5月12日"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,message=FALSE}
#Import package tidyverse
library(tidyverse)
library(ggplot2)
library(magrittr)
library(dplyr)
```

```{r}
#Simple graph
dim(mpg)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = class, y = drv))

#Using aesthetic to change point appearance (categorical)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,color=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,size=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,alpha=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,shape=class))

#Using aesthetic to change point appearance (continuous)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,color=cty))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,size=cty))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,alpha=cty))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,shape=cty))

#Stroke aesthetic

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy,stroke=cyl))


```

#Using facets

##One variable
```{r}
#Two rows
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)

#One row
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(. ~ cyl)

```

##Two variables

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```

#Using different geoms

```{r}
# left
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

# right
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))

#Different line by cat variables using linetype in aesthetic
ggplot(data = mpg,aes(x = displ, y = hwy, linetype = drv)) + 
  geom_smooth()
```

```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
    
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )
```

#Different geoms in a same plot

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

#Global mapping/Local mapping

```{r}
#Global mapping
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
#Local mapping
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()

#Subset in local mapping
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
```

#Histogram

```{r}
ggplot(data = mpg, mapping = aes(x = displ)) + 
  geom_histogram()
```

#Histogram with calculated values

```{r}
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")
```

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```
#Summary statistics
```{r}
#Summary
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

#Geom_col

```{r}
ggplot(data = diamonds) + 
  geom_col(mapping = aes(x = cut,y=table))
```

#Position adjustment

```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")

#Bar same size
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

#Bar horizontally splitted
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

#Adding noise to avoid data point rounding
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
```

##Exercize

```{r}
#adding jitter
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_jitter()
```

##Coordinates

```{r}
#Change orientation of axis
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()

#Polar coordinates
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar(theta="x") + labs(title = "Cylinders")
```

##Distribution

```{r}
#Setting density instead of count for freqpoly
ggplot(data = diamonds, mapping = aes(x = price, y = ..density..)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 500)
```

```{r}
#Reordering categorical variable order according to the median (FUN argument)
ggplot(data = mpg) +
  geom_boxplot(mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy))
```

```{r}
#Visualising the count for 2 categorical variables
diamonds %>% 
  count(color, cut) %>%  
  ggplot(mapping = aes(x = color, y = cut)) +
    geom_tile(mapping = aes(fill = n))
```

```{r}
#Creating 2d bins
ggplot(data = diamonds) +
  geom_bin2d(mapping = aes(x = carat, y = price))
```

